services:
  backend:
    image: ghcr.io/mertk69/ki-assistent-backend:latest
    container_name: ki-assistent-backend-1
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8091:8000"  # Intern 8000 (FastAPI), Extern 8091

  frontend:
    image: ghcr.io/mertk69/ki-assistent-frontend:latest
    container_name: ki-assistent-frontend-1
    restart: always
    ports:
      - "8092:3000"  # Intern 3000 (Next.js), Extern 8092
    depends_on:
      - backend
